<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZbjrtbi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZbjrtbi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZbjrtbi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZbjrtbi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZbjrtbi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zbjrtbi',
    'container.build_id' => '05e744a8',
    'container.build_time' => 1764337967,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZbjrtbi');
