<?php

namespace ContainerZbjrtbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DqOYEKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dqOY_EK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dqOY_EK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'goal' => ['privates', '.errored..service_locator.dqOY_EK.App\\Entity\\Goal', NULL, 'Cannot autowire service ".service_locator.dqOY_EK": it needs an instance of "App\\Entity\\Goal" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'goal' => 'App\\Entity\\Goal',
            'em' => '?',
        ]);
    }
}
