<?php

namespace ContainerZbjrtbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TdTHOQc.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TdTHOQc.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'weatherService' => ['privates', 'App\\Service\\WeatherService', 'getWeatherServiceService', true],
            'newsService' => ['privates', 'App\\Service\\NewsService', 'getNewsServiceService', true],
            'financeService' => ['privates', 'App\\Service\\FinanceService', 'getFinanceServiceService', true],
        ], [
            'entityManager' => '?',
            'weatherService' => 'App\\Service\\WeatherService',
            'newsService' => 'App\\Service\\NewsService',
            'financeService' => 'App\\Service\\FinanceService',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
