<?php

namespace ContainerZbjrtbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinanceServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FinanceService' shared autowired service.
     *
     * @return \App\Service\FinanceService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FinanceService.php';

        return $container->privates['App\\Service\\FinanceService'] = new \App\Service\FinanceService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
