<?php

namespace ContainerZbjrtbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoalControllertoggleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dqOY_EK.App\Controller\GoalController::toggle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.dqOY_EK'] ?? $container->load('get_ServiceLocator_DqOYEKService'));

        if (isset($container->privates['.service_locator.dqOY_EK.App\\Controller\\GoalController::toggle()'])) {
            return $container->privates['.service_locator.dqOY_EK.App\\Controller\\GoalController::toggle()'];
        }

        return $container->privates['.service_locator.dqOY_EK.App\\Controller\\GoalController::toggle()'] = $a->withContext('App\\Controller\\GoalController::toggle()', $container);
    }
}
