<?php

namespace ContainerZbjrtbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoalTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\GoalType' shared autowired service.
     *
     * @return \App\Form\GoalType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/GoalType.php';

        return $container->privates['App\\Form\\GoalType'] = new \App\Form\GoalType();
    }
}
