<?php

namespace ContainerZbjrtbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoalControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GoalController' shared autowired service.
     *
     * @return \App\Controller\GoalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GoalController.php';

        $container->services['App\\Controller\\GoalController'] = $instance = new \App\Controller\GoalController();

        $instance->setContainer(($container->privates['.service_locator.5k8W8mg'] ?? $container->load('get_ServiceLocator_5k8W8mgService'))->withContext('App\\Controller\\GoalController', $container));

        return $instance;
    }
}
